### ISSUE TITLE
Some End-to-End tests require authentication

### ISSUE THREAD

**Issue by msrb** [fabric8-analytics/fabric8-analytics-common#158]
Since tests now run against deployment in OpenShift, where authentication is enabled, we will need API tokens in CI (jobs and API services).

**Comment by msrb** [comment]
cc @samuzzal-choudhury 

This is going to be a problem for all non-trivial tests.

**Comment by samuzzal-choudhury** [comment]
@msrb can RECOMMENDER_API_TOKEN env variable be used for that purpose?

**Comment by msrb** [comment]
@samuzzal-choudhury AFAIK, not out-of-the-box, changes in the test suite will be needed. The question also is where do we get the token that will be used by the tests :)

**Comment by samuzzal-choudhury** [comment]
@msrb I understand that the test suite will have to be updated to consume RECOMMENDER_API_TOKEN. I am working with Shovik to get the offline token for the staging env.

**Comment by msrb** [comment]
@samuzzal-choudhury thanks :)

**Comment by tisnik** [comment]
@msrb @samuzzal-choudhury it won't be a big problem to use ```RECOMMENDER_API_TOKEN```, I'm just not sure how to distinguish between the environment. I.e. on staging we would need to use the ```RECOMMENDER_API_TOKEN``` whereas on local/docker environment we need to use generated token - am I right?

**Comment by tisnik** [comment]
Please see #162

**Comment by tisnik** [comment]
Everything looks ok on my side: ```ECOMMENDER_API_TOKEN``` is provided, test machinery uses it and test has been updated as well. Ok to close?

**Comment by msrb** [comment]
We can close this one, thanks @tisnik and @samuzzal-choudhury :)
