### ISSUE TITLE
Update registry URL for pushing images

### ISSUE THREAD

**Issue by tuxdna** [fabric8-analytics/fabric8-analytics-common#238]
This issue is opened to track progress of this Trello: https://trello.com/c/zLOXKyW1/712-switch-to-pushregistrydevshiftnet

Changes made so far:

 * [x] https://github.com/fabric8-analytics/gremlin-docker/pull/13
 * [x] https://github.com/fabric8-analytics/fabric8-analytics-data-model/pull/42
 * [x] https://github.com/fabric8-analytics/fabric8-analytics-server/pull/127
 * [x] https://github.com/fabric8-analytics/fabric8-analytics-recommender/pull/9
 * [x] https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/146
 * [x] https://github.com/fabric8-analytics/fabric8-analytics-cvedb-s3-dump-docker/pull/2
 * [x] https://github.com/fabric8-analytics/anitya-docker/pull/9

Update 2

 * [x] https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/273
 * [x] https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/pull/39
 * [x] https://github.com/fabric8-analytics/fabric8-analytics-worker-base/pull/2
 * [x] https://github.com/fabric8-analytics/fabric8-analytics-firehose-fetcher/pull/4
 * [x] https://github.com/fabric8-analytics/fabric8-analytics-license-analysis/pull/9

**Comment by msrb** [comment]
Thanks! All merged. Please take a look also at:

- https://github.com/fabric8-analytics/fabric8-analytics-worker
- https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis
- https://github.com/fabric8-analytics/fabric8-analytics-worker-base
- https://github.com/fabric8-analytics/fabric8-analytics-firehose-fetcher
- https://github.com/fabric8-analytics/fabric8-analytics-license-analysis

**Comment by tuxdna** [comment]
@msrb: Update 2 covers rest of the repos. Please review.

**Comment by msrb** [comment]
Thanks @tuxdna, all merged 😉

**Comment by tuxdna** [comment]
@msrb Thanks, that was quick ;-)
