### ISSUE TITLE
How to deploy to OpenShift ?

### ISSUE THREAD

**Issue by tuxdna** [fabric8-analytics/fabric8-analytics-common#454]
Deploying on DevCluster ( OpenShift ) can be done using deploy.sh script as described in [README.md](https://github.com/fabric8-analytics/fabric8-analytics-common/blob/cbbb47c7932f04ba12cb1b67855153e7b10dd2b2/openshift/README.md )

However this process hasn't worked for me yet. 

![deploy-on-oc](https://user-images.githubusercontent.com/52947/35039797-f55d5794-fba4-11e7-8bd6-e1cca944a7f2.png)

As shown in the image, many services fail to run for me.

An updated documentation is required that describes:

 * what are minimum configuration parameters that must be provided in env.sh file?
 * how to obtain these parameters?

**Comment by jpopelka** [comment]
Some improvements are (not yet merged) in #452

**Comment by tuxdna** [comment]
@jpopelka Thanks. I will try those changes.

**Comment by tuxdna** [comment]
On second attempt I encountered three failing deployments:

 * bayesian-kronos-pypi-1-deploy
 * f8a-worker-scaler-2-deploy
 * bayesian-kronos-maven-1-deploy


Following image shows them

![screenshot from 2018-01-18 19-06-03](https://user-images.githubusercontent.com/52947/35100705-c8b16bf2-fc82-11e7-99f6-42dffeed8f45.png)

**Comment by tuxdna** [comment]
I believe we need more documentation around how to access Jobs API once deployed to Dev Cluster?

Usually we have go make a `/generate-token` call to access the OAuth2 token before we can do anything useful with Jobs API. However to generate OAuth2 token, we need correct values for OAuth2 settings here:

https://github.com/fabric8-analytics/fabric8-analytics-common/blob/7171772f4523f00622099b644772c3784a8fb58b/openshift/env-template.sh#L20-L24

Whenever I access https://github.com/organizations/fabric8-analytics/settings/applications , I get 404 NOT FOUND error.

**Comment by jpopelka** [comment]
More in https://github.com/fabric8-analytics/fabric8-analytics-deployment/pull/16

@tuxdna have your questions been answered or do we need to move this ticket to https://github.com/fabric8-analytics/fabric8-analytics-deployment ?

**Comment by tuxdna** [comment]
This is resolved. Marking as closed.
