### ISSUE TITLE
Do we need the `gemini_fix` branch?

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-common#731]
@yzainee do we really need the `gemini_fix` branch? If not, please delete it or ask me to do so.

https://github.com/fabric8-analytics/fabric8-analytics-common/branches

```
 Active branches

    gemini_fix
    Updated 3 months ago by Yusuf Zainee 
```

**Comment by yzainee** [comment]
unused branch deleted

**Comment by tisnik** [comment]
cool, TYVM @yzainee
