### ISSUE TITLE
RFE: don't shadow id() function by parameter and local variable names in the common.py module

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-common#76]
id() function is shadowed by parameters and local variables with the same name in the common.module

**Comment by tisnik** [comment]
Fixed in #77

**Comment by fridex** [comment]
Just a tip: you can close issues via commit messages [1]. Could save some time (and keep issues clean).

[1] https://help.github.com/articles/closing-issues-via-commit-messages/
